### PR TITLE
Implement downloading & Filtering

### PR DESCRIPTION
**Pull request by DraxCodes**
Currently we have the following completed/In progress.

- [x] Save stream locally
- [x] Search by title
- [x] Search by title & duration
- [x] Search by title & duration with some room for error (within 5-10 secs)
- [x] Search by Title - Author (Should maybe replace the simple search by title)
- [x] Search by Title - Author Lyrics (Should prob be it's own extension so we have a fallback)
- [x] Search by Title - Author - Duration
- [x] Search by Title - Author - Duration Lyrics

ℹ️ To keep it simple, for the search methods that append "lyrics" we should prob simple make that a bool on each extension method. So an example of search could be like: 
```cs
public Video FilerBy(this IReadonlyList<Video> videos, string title, string author, bool appendLyrics)
{
}
```

### CODE REVIEW

**Comment by svr333** [comment]
Will start working after dinner, approx. 1hour, 1hour and a half

Edit: Didn't get to it due to having too much fun in Rocket League, will start working on it tomorrow morning then :)

**Comment by DraxCodes** [comment]
Overall the added changes do a couple things:

* Searching for a track with author & lyrics or without is now handled by: 
    * ` await _downloadService.DownloadMediaAsync(track: track, filePath: "Music", appendLyrics: true, useAuthor: true)`
* Saved filenames are now safe and should always replace illegal chars with an underscore.
* try/catch blocks for previously unknown exceptions that could be thrown.

⚠️ NOTE: The Console.WriteLines() will eventually be replaced with a LogEvent as per #14 
This was mentioned also in the commit "Big refactor"

**Comment by DraxCodes** [comment]
Big new feature added: (I figured this would be the best time to add it as after this PR we really want to be building Ui's rather than working on the backend).

This code snippet outlines the new feature. It is meant as a UI side search function, it's not the prettiest but it works for now and adds something I think the UI's would 100% need. 

```cs
public async Task YoutubeSearchAndDownloadTest()
{
	//User would enter a search which we use to generate a Track entity.
	Console.WriteLine("Please enter a title");
	var title = Console.ReadLine();
	
	//Yes Author is 100% required in this useCase, however we could make this optional if you feel it's needed.
	Console.WriteLine("Please Enter the Author");
	var author = Console.ReadLine();

	//Generate the track entity within the UI. (Set duration to 0 as we don't care about that in this useCase)
	var searchTrack = new Track(title, new[] { author }, 0);

	//Search the stream repo for the tracks assocaited with the users query (Essentially searching youtube)
	var ytTracks = await _streamRepository.SearchAsync(searchTrack);

	//Display results (At this point you have YoutubeTrack entities which have an ID associated with them)
	foreach (var track in ytTracks)
	{
		Console.WriteLine($"{track.Title} : {track.Id}");
	}

	//Here we could do a few things, in this example I am getting them to enter an ID because it's a console UI. 
	//In your UI you could have a selection box or whatever, essentially you just need to be able to get the YoutubeTrack ID based on what the user selected.
	Console.WriteLine("\nPlease enter an ID from the options above.");

	var id = Console.ReadLine();

	//Now we select the track using Linq, again ensure this is by ID as it'll be the most secure way of doing it.
	var selectedTrack = ytTracks.FirstOrDefault(t => t.Id == id);

	//Pass the selected track to the download service, specify as directory as always.
	//Save filename is the same format as with spotify except now we use Youtube title and author for obvious reasons.
	//Note that this is a new method specific to YoutubeTracks, in the future I will make this cleaner. For now I was going for readability / self documenting.
	await _downloadService.DownloadMediaFromYoutubeTrackAsync(selectedTrack, "Test");

	Console.WriteLine($"Download: {selectedTrack.Title} Completed.");
}
```

**Review by svr333 — APPROVED** [review]
Looks good to me dude!
Let's get started on those UI's 😉

**Pull request merged**
